#Database Configuration
spring:
  datasource:
    url: ------------------
    username: -------------------
    password: ------------------
    driverClassName: ------
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      fail-on-empty-beans: false
      wrap-root-value: true



server:
  port: 8088
  address: 0.0.0.0

#Logging Configuration
logging:
  file: main.log
  path: log
  level:
    root: INFO
    org.springframework.security: INFO
    com.datasirpi.appointment.manager.user.service: INFO

dependency:
  groupId: org.springframework.boot
  artifactId: spring-boot-starter-security

elasticsearch:
  clustername: docker-cluster
  host: localhost
  port: 9300

trojan:
  encrypt:
    ivparam: --------------------
    key: ----------------




